"""
make_figure_5A.py — The Spine, Figure 5.A: the regime placement
World Tree Project · July 2026

Renders §5.7's two-axis placement: spectral entropy of sustained behavior
(x) against stationarity, the coefficient of variation of that entropy
across each substrate's own repetition axis (y).

Discipline (the §5.7 estimator caveat, enforced by construction):
  · Every plotted value is either a PUBLISHED number (source cited beside
    each constant below) or is regenerated here by the grid implementation
    that reproduces the published §3.5 table exactly (same estimator).
  · Substrates whose windowed dispersion was never published numerically
    (the Mathematica F_c recurrence and the Mathematica grid) are drawn as
    rug ticks on the SE axis — known x, unpublished y — not given invented
    stationarity values.
  · The placement is a typed comparison across estimators and signals — a
    correspondence of signature class, not an identity of value (§5.7).
    Adding this figure changes no register: the lock-regime reading
    remains PROPOSED.

Open gate carried forward (§5.1 [Editorial:] bracket): the registered
threshold wording must be verified verbatim against the timestamped
pre-registration. This figure draws the 0.15 line as applied in the §5.6
scorecard and the 0.30 strong-positive line from §5.1. If the verbatim
check resolves differently, change THRESHOLDS below and re-run — the
figure regenerates deterministically.

Deterministic: seed 42 throughout. Output: fig_5A_regime_placement.png (300 dpi).
"""

import numpy as np
import math
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

PHI = (1 + math.sqrt(5)) / 2

# ================================================================
# 1. Grid backbone — SE(k), regenerated by the verified implementation
#    (reproduces Spine §3.5: 0.4932 @0.221, 0.4847 @2/9, 0.348 @0.223, …)
# ================================================================
OMEGA = 2 * np.pi * 60
STEPS = 2000
DT = 1.0 / 3600
SEED = 42

def build_grid(n=100):
    ga = 2 * np.pi / PHI**2
    pos = np.array([[math.sqrt(i + 1) * 0.5 * math.cos(i * ga),
                     math.sqrt(i + 1) * 0.5 * math.sin(i * ga)] for i in range(n)])
    adj = np.zeros((n, n))
    for i in range(n):
        d = np.linalg.norm(pos - pos[i], axis=1); d[i] = np.inf
        for j in np.argsort(d)[:5]:
            w = 1 / (1 + d[j]); adj[i, j] = w; adj[j, i] = w
    rs = adj.sum(1, keepdims=True); rs[rs == 0] = 1
    return adj / rs

def grid_se(k_fc, adj, n=100, coupling=0.05):
    np.random.seed(SEED)
    t = np.arange(STEPS) * DT
    loads = np.zeros((n, STEPS))
    for i in range(n):
        base = 0.05 * np.sin(2 * np.pi * 0.1 * t + i * PHI * 0.3)
        h3 = 0.05 * np.sin(3 * OMEGA * t + np.random.uniform(0, 2 * np.pi))
        h5 = 0.03 * np.sin(5 * OMEGA * t + np.random.uniform(0, 2 * np.pi))
        h7 = 0.02 * np.sin(7 * OMEGA * t + np.random.uniform(0, 2 * np.pi))
        sp = np.zeros(STEPS)
        for _ in range(np.random.randint(5, 15)):
            loc = np.random.randint(0, STEPS); w = np.random.randint(5, 20)
            a = np.random.uniform(0.10, 0.25) * np.random.choice([-1, 1])
            s, e = max(0, loc - w // 2), min(STEPS, loc + w // 2); sp[s:e] = a
        loads[i] = base + h3 + h5 + h7 + sp + 0.01 * np.random.randn(STEPS)
    vh = np.zeros((n, STEPS)); vc = np.ones(n); vp = np.ones(n)
    ph = np.arange(n) * (2 * np.pi / PHI**2)
    for step in range(STEPS):
        tv = step * DT
        vn = vc + loads[:, step] * DT * 10
        vn = vn + coupling * (adj @ vn - vn)
        dp, dc = vp - 1, vn - 1
        vn = vn + k_fc * (3 * dp - 6 * dc)
        amp = np.std(dc) * 0.3
        vn = vn - amp * (np.sin(3 * OMEGA * tv + ph) + np.sin(6 * OMEGA * tv + ph) + np.sin(9 * OMEGA * tv + ph))
        dev = vn - 1; wr = np.fmod(dev + PHI, 2 * PHI); wr = np.where(wr < 0, wr + 2 * PHI, wr)
        vn = wr - PHI + 1
        vp = vc.copy(); vc = vn.copy(); vh[:, step] = vc
    se = []
    for i in range(n):
        pw = np.abs(np.fft.rfft(vh[i])[1:])**2
        if pw.sum() < 1e-12: se.append(0.0); continue
        p = pw / pw.sum(); p = p[p > 1e-12]
        se.append(-(p * np.log(p)).sum() / np.log(len(p)))
    return float(np.mean(se))

print("Regenerating grid backbone SE(k) …")
adj = build_grid(100)
k_track = [0.150, 0.170, 0.190, 0.205, 0.215, 0.219, 0.221, 2/9, 0.223, 0.2261, 0.2295]
se_track = [grid_se(k, adj) for k in k_track]
for k, s in zip(k_track, se_track):
    print(f"  k={k:.4f}  SE={s:.4f}")

# ================================================================
# 2. Published constants (source beside each)
# ================================================================
GRID_SE, GRID_COV = 0.4993, 0.0113 / 0.4993          # Spine §3.3 (25–1,000 nodes)
E8_TRIO = [0.4932, 0.4989, 0.4996]                    # Spine §3.5 (2D / 600-cell / E8 @ k=0.221)
E8_COV = float(np.std(E8_TRIO) / np.mean(E8_TRIO))    # dispersion across topologies (from §3.5 values)
MATH_FC_SE = 0.495                                    # BatF §4 / Table 4 (windowed; dispersion unpublished)
MATH_GRID_SE = 0.4950                                 # BatF Table 4 (dispersion unpublished)
BOX_C = [46.5, 45.5, 47.9, 48.8, 48.6, 49.4, 49.8, 50.3, 50.2, 50.7, 50.3, 50.2]  # BatF Table 3 C%
BOX_SE, BOX_COV = float(np.mean(BOX_C)) / 100, float(np.std(BOX_C) / np.mean(BOX_C))
ORB_SE, ORB_COV = 0.2548, 0.048                       # Spine §5.5 (combined, 1-yr windows, 293 windows)
SCALE_CURVE = [0.2677, 0.2447, 0.2421, 0.2486, 0.2548, 0.2517, 0.2293, 0.2152, 0.2060,
               0.1936, 0.1865, 0.1767, 0.1703, 0.1657, 0.1576, 0.1527, 0.1489, 0.1426, 0.1382]  # Table 5.14 CB actual
THRESHOLDS = [(0.15, "0.15 — full-span line (§5.6)"),
              (0.30, "0.30 — strong positive (§5.1)")]  # registered SE reference lines
BAND = (0.48, 0.51)                                   # invariant monitor band (§3.6)

# ================================================================
# 3. Render
# ================================================================
fig, ax = plt.subplots(figsize=(8.6, 5.4), dpi=300)
ink, paper = "#2b2620", "#ffffff"
gold, blue, grey = "#b8860b", "#3b5b7d", "#8a8378"
ax.set_facecolor(paper)

# invariant band + registered thresholds
ax.axvspan(BAND[0], BAND[1], color="#e9e2d0", alpha=0.55, lw=0, zorder=0)
ax.text(np.mean(BAND), 0.0655, "invariant band (§3.6)", ha="center", fontsize=7.5, color=grey)
for th, lab in THRESHOLDS:
    ax.axvline(th, ls=(0, (4, 3)), lw=0.9, color=grey, zorder=1)
    ax.text(th, 0.0655, lab, rotation=0, ha="center", fontsize=7.5, color=grey)

# grid backbone track at the grid's own stationarity level
y_track = GRID_COV
order = np.argsort(se_track)
ax.plot(np.array(se_track)[order], [y_track] * len(se_track), "-", lw=1.0, color=blue, alpha=0.45, zorder=2)
ax.plot(se_track, [y_track] * len(se_track), "o", ms=2.6, color=blue, alpha=0.55, zorder=3)
for k, s, lab in [(0.150, se_track[0], "k=0.150"), (0.221, se_track[6], "0.221"),
                  (0.223, se_track[8], "lock 0.223"), (0.2295, se_track[10], "0.2295 (post-cliff,\nnot stationary)")]:
    ax.annotate(lab, (s, y_track), textcoords="offset points", xytext=(0, -14),
                ha="center", fontsize=6.8, color=blue)
ax.annotate("energy-grid SE(k) backbone", (se_track[3], y_track), textcoords="offset points",
            xytext=(0, 9), ha="center", fontsize=7.5, color=blue)

# full 2D markers (published dispersion)
ax.plot(GRID_SE, GRID_COV, "o", ms=8, color=blue, mec=ink, mew=0.6, zorder=5)
ax.annotate("Python grid, 25–1,000 nodes (§3.3)", (GRID_SE, GRID_COV),
            textcoords="offset points", xytext=(10, 6), fontsize=7.5, color=ink)
ax.plot(np.mean(E8_TRIO), E8_COV, "^", ms=7.5, color="#5b7d3b", mec=ink, mew=0.6, zorder=5)
ax.annotate("2D · 600-cell · E8 (§3.5; spread 0.0064)", (np.mean(E8_TRIO), E8_COV),
            textcoords="offset points", xytext=(10, -3), fontsize=7.5, color=ink)
ax.plot(BOX_SE, BOX_COV, "D", ms=7, mfc="none", mec="#7d3b5b", mew=1.3, zorder=5)
ax.annotate("Boχ (C% correlate, 12 inputs — BatF Table 3)", (BOX_SE, BOX_COV),
            textcoords="offset points", xytext=(-6, 9), ha="right", fontsize=7.5, color="#7d3b5b")

# orbital point + the §5.13 scale curve behind it
ax.plot(SCALE_CURVE, [ORB_COV] * len(SCALE_CURVE), "o", ms=2.2, color=gold, alpha=0.35, zorder=3)
ax.plot([min(SCALE_CURVE), max(SCALE_CURVE)], [ORB_COV] * 2, "-", lw=0.9, color=gold, alpha=0.35, zorder=2)
ax.plot(ORB_SE, ORB_COV, "*", ms=15, color=gold, mec=ink, mew=0.6, zorder=6)
ax.annotate("Earth–Moon–Sun combined ratio (§5.5)\n1-yr windows; §5.13 scale curve behind\namplitude bounded [96, 120] — §5.6 PASS",
            (ORB_SE, ORB_COV), textcoords="offset points", xytext=(8, 8), fontsize=7.5, color="#7a5a08")

# rug tick: published SE, dispersion not numerically published.
# F_c 0.495 and Mathematica grid 0.4950 are coincident at published
# precision (BatF Table 4) — one tick, dual label, x unmodified.
ax.plot([MATH_FC_SE, MATH_FC_SE], [0.0005, 0.0035], "-", lw=1.8, color=ink, zorder=4)
ax.annotate("Mathematica F_c 0.495 · Mathematica grid 0.4950\n(coincident at published precision — BatF Table 4;\nSE published, windowed dispersion not)", (0.4925, 0.004),
            textcoords="offset points", xytext=(-4, 2), ha="right", fontsize=6.8, color=ink)

ax.set_xlim(0.10, 0.80)
ax.set_ylim(0, 0.07)
ax.set_xlabel("spectral entropy of sustained behavior (each substrate's published estimator)", fontsize=9)
ax.set_ylabel("stationarity — CoV of SE across the substrate's\nown repetition axis (windows · scales · topologies · inputs)", fontsize=9)
ax.set_title("Figure 5.A — Regime placement: the invariant cluster, the grid's SE(k) curve, and the orbital point",
             fontsize=10, color=ink, pad=10)
for s in ["top", "right"]:
    ax.spines[s].set_visible(False)
ax.tick_params(labelsize=8)
fig.tight_layout()
fig.savefig("fig_5A_regime_placement.png", dpi=300, facecolor=paper)
print("\nSaved fig_5A_regime_placement.png")
print(f"E8 trio CoV (from §3.5 values): {E8_COV:.4f} | Boχ correlate: ({BOX_SE:.4f}, {BOX_COV:.4f})")
